### ISSUE TITLE
Add CakePHP (in progress)

### ISSUE THREAD

**Issue by dereuromark** [komarserjio/notejam#22]
Any plans on adding CakePHP?
Either 2.x or the new 3.x version maybe?

I think as one of the oldest (first ever, 10+ years) and most major frameworks out there it should most definitely be in that list.

**Comment by komarserjio** [comment]
Hey @williamn. How does it go with the cakephp app?
If it goes not very well, I would like to assign this issue to me and implement the cakephp version.

**Comment by williamn** [comment]
Hey @komarserjio 

I dont really have enough time to completed. Please assign someone else.

Do you want to me to pull request my latest changes? I have implemented  Sign Up

**Comment by komarserjio** [comment]
Hi @dereuromark. I've finally finished CakePHP version :). 
https://github.com/komarserjio/notejam/tree/master/cakephp
Would be great if you could take a look on the implementation before I announce it on the web. 

@lorenzo would be happy to get your feedback  :)

**Comment by lorenzo** [comment]
My feedback:

* It would be nice to remove this line: https://github.com/komarserjio/notejam/blob/master/cakephp/notejam/config/routes.php#L73
* It would be easier to show how the query builder works if you move the contain to its own method https://github.com/komarserjio/notejam/blob/master/cakephp/notejam/src/Controller/NotesController.php#L36
* You can change this with `firstOrFail()` https://github.com/komarserjio/notejam/blob/master/cakephp/notejam/src/Controller/NotesController.php#L136
* The `Time` class already has a method for this https://github.com/komarserjio/notejam/blob/master/cakephp/notejam/src/Model/Entity/Note.php#L33
* The `input()` function has a `empty =>` option for doing what you are doing here https://github.com/komarserjio/notejam/blob/master/cakephp/notejam/src/Template/Element/notes/form.ctp#L4
* It makes more sense to set the current logged in user in the controller, instead of reading the session in the template https://github.com/komarserjio/notejam/blob/master/cakephp/notejam/src/Template/Layout/default.ctp#L18
* Instead of repeating what you already did in the Form class, you can use here `$this->Form->allInputs()` https://github.com/komarserjio/notejam/blob/master/cakephp/notejam/src/Template/Users/settings.ctp#L4-L6

The code looks really good! I had to look hard for things I would do differently :)

**Comment by komarserjio** [comment]
@lorenzo thank you :) Really valuable comments, will change things.

**Comment by dereuromark** [comment]
Yeah in general you should try to use DashedRoute.

**Comment by lorenzo** [comment]
@komarserjio One last thing. You can avoid some repetition here and in the other scopes:

https://github.com/komarserjio/notejam/blob/master/cakephp/notejam/config/routes.php#L59-L64

By setting the controller default in the scope definition:

```php
 $routes->scope('/pads', ['controller' => 'Pads'], function($routes) { // Default added here
        $routes->connect('/create', ['action' => 'create'], ['_name' => 'create_pad']);
        $routes->connect('/:id/edit', ['action' => 'edit'], ['id' => '\d+', 'pass' => ['id'], '_name' => 'edit_pad']);
        $routes->connect('/:id/delete', ['action' => 'delete'], ['id' => '\d+', 'pass' => ['id'], '_name' => 'delete_pad']);
        $routes->connect('/:id', ['action' => 'view'], ['id' => '\d+', 'pass' => ['id'], '_name' => 'view_pad']);
    });
```

**Comment by komarserjio** [comment]
@lorenzo this is smart. I didn't know about defaults for scope definitions.
